# Generated by Django 3.2.1 on 2024-03-14 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('nfcs', 'Nfcs'), ('catechism', 'Catechism'), ('life_of_saints', 'Life Of Saints'), ('school', 'School'), ('accommodation', 'Accommodation'), ('alumni', 'Alumni'), ('exams', 'Exams'), ('pious_society', 'Pious Society'), ('chaplaincy', 'Chaplaincy'), ('bible', 'Bible'), ('eucharist', 'Eucharist')], default='nfcs', max_length=75)),
                ('excerpt', models.CharField(max_length=150)),
                ('month', models.CharField(max_length=3)),
                ('day', models.CharField(max_length=2)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('thumbnail1', models.ImageField(blank=True, null=True, upload_to='Photos/%Y/%m/%d')),
                ('thumbnail2', models.ImageField(blank=True, null=True, upload_to='Photos/%Y/%m/%d')),
                ('thumbnail3', models.ImageField(blank=True, null=True, upload_to='Photos/%Y/%m/%d')),
                ('thumbnail4', models.ImageField(blank=True, null=True, upload_to='Photos/%Y/%m/%d')),
                ('thumbnail5', models.ImageField(blank=True, null=True, upload_to='Photos/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=13)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_alumni', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('visitors', models.BooleanField(default=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
