# Generated by Django 4.2.4 on 2023-11-28 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('nfcs', 'Nfcs'), ('catechism', 'Catechism'), ('life_of_saints', 'Life Of Saints'), ('school', 'School'), ('accommodation', 'Accommodation'), ('alumni', 'Alumni'), ('exams', 'Exams'), ('pious_society', 'Pious Society'), ('chaplaincy', 'Chaplaincy'), ('bible', 'Bible'), ('eucharist', 'Eucharist')], default='nfcs', max_length=75)),
                ('excerpt', models.CharField(max_length=150)),
                ('month', models.CharField(max_length=3)),
                ('day', models.CharField(max_length=2)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('thumbnail1', models.ImageField(blank=True, null=True, upload_to='Photos/%Y/%m/%d')),
                ('thumbnail2', models.ImageField(blank=True, null=True, upload_to='Photos/%Y/%m/%d')),
                ('thumbnail3', models.ImageField(blank=True, null=True, upload_to='Photos/%Y/%m/%d')),
                ('thumbnail4', models.ImageField(blank=True, null=True, upload_to='Photos/%Y/%m/%d')),
                ('thumbnail5', models.ImageField(blank=True, null=True, upload_to='Photos/%Y/%m/%d')),
            ],
        ),
    ]
