# Generated by Django 4.2.4 on 2023-11-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0002_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
