# Generated by Django 3.2.1 on 2024-03-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0004_alter_blogpost_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
